name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - jupyterlab-myst
  - cartopy
  - earthaccess
  - geopandas
  - matplotlib
  - mystmd
  - numpy
  - pyproj
  - rioxarray
  - sliderule
