name: cookbook-dev
channels:
- conda-forge
- nodefaults
dependencies:
- cartopy *
- matplotlib *
- pre-commit *
- jupyterlab *
- jupyterlab-myst *
- earthaccess *
- geodatasets *
- geopandas *
- icepyx *
- ipympl *
- ipykernel *
- mystmd *
- numpy *
- pyproj *
- rioxarray *
- sliderule *
- xarray *
- h5py *
