name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - accessible-pygments=0.0.5
  - alabaster=0.7.16
  - anyio=4.9.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.6.15
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.2.1
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - docutils=0.21.2
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fqdn=1.5.1
  - gitdb=4.0.12
  - gitpython=3.1.44
  - greenlet=3.2.3
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagesize=1.4.1
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.24.0
  - jupyter-book=1.0.4.post1
  - jupyter-cache=1.0.1
  - jupyter-lsp=2.2.5
  - jupyter-server-mathjax=0.2.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.4
  - jupyterlab-favorites=3.2.2
  - jupyterlab-git=0.51.2
  - jupyterlab-myst=2.4.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - jupytext=1.17.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - latexcodec=2.0.1
  - ld_impl_linux-64=2.43
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsodium=1.0.20
  - libsqlite=3.50.2
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.38.1
  - libuv=1.51.0
  - libzlib=1.3.1
  - linkify-it-py=2.0.3
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.4.2
  - mdurl=0.1.2
  - mistune=3.1.3
  - myst-nb=1.2.0
  - myst-parser=3.0.1
  - mystmd
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbdime=4.0.2
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nodejs=22.13.0
  - notebook-shim=0.2.4
  - openssl=3.5.0
  - overrides=7.7.0
  - packaging=25.0
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybtex=0.25.1
  - pybtex-docutils=1.0.3
  - pycparser=2.22
  - pydata-sphinx-theme=0.15.4
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.13.5
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python_abi=3.13
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.25.1
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - smmap=5.0.2
  - sniffio=1.3.1
  - snowballstemmer=3.0.1
  - soupsieve=2.7
  - sphinx=7.4.7
  - sphinx-book-theme=1.1.4
  - sphinx-comments=0.0.3
  - sphinx-copybutton=0.5.2
  - sphinx-design=0.6.1
  - sphinx-external-toc=1.0.1
  - sphinx-jupyterbook-latex=1.0.0
  - sphinx-multitoc-numbering=0.1.3
  - sphinx-thebe=0.3.1
  - sphinx-togglebutton=0.3.2
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-bibtex=2.6.5
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlalchemy=2.0.41
  - stack_data=0.6.3
  - tabulate=0.9.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250516
  - typing-extensions=4.14.0
  - typing_extensions=4.14.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - uc-micro-py=1.0.3
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0