name: trigger-book-build
on:
  pull_request_target:
    types: [labeled, synchronize]
    branches:
      - main

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    secrets:
      EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
      EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
    with:
      artifact_name: book-zip-${{ github.event.number }}
      base_url: '/${{ github.event.repository.name }}/_preview/${{ github.event.number }}'
      # Other input options are possible, see ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml
